"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 17:20:28.339327
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import openbackup.db.models

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('login_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_failures_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_failures_ip'), ['ip'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('local', 'nfs', name='repokind', native_enum=False), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('nfs_server', sa.String(length=255), nullable=False),
    sa.Column('nfs_export', sa.String(length=1024), nullable=False),
    sa.Column('nfs_options', sa.String(length=255), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('passphrase_enc', sa.Text(), nullable=True),
    sa.Column('capacity_bytes', sa.BigInteger(), nullable=True),
    sa.Column('free_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'operator', 'admin', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', openbackup.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vcenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('thumbprint', sa.String(length=128), nullable=False),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('datastore_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vcenter_id', sa.Integer(), nullable=False),
    sa.Column('datastore', sa.String(length=255), nullable=False),
    sa.Column('nfs_server', sa.String(length=255), nullable=False),
    sa.Column('nfs_export', sa.String(length=1024), nullable=False),
    sa.Column('nfs_options', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vcenter_id'], ['vcenters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vcenter_id', 'datastore')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vcenter_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('vms', sa.JSON(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('retention_points', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('quiesce', sa.Boolean(), nullable=False),
    sa.Column('active_full_days', sa.Integer(), nullable=False),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('next_run_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['vcenter_id'], ['vcenters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restore_points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('vm_uuid', sa.String(length=64), nullable=False),
    sa.Column('vm_name', sa.String(length=255), nullable=False),
    sa.Column('vm_moref', sa.String(length=64), nullable=False),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('logical_bytes', sa.BigInteger(), nullable=False),
    sa.Column('read_bytes', sa.BigInteger(), nullable=False),
    sa.Column('new_bytes', sa.BigInteger(), nullable=False),
    sa.Column('disks', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restore_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restore_points_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_points_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_points_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restore_points_vm_uuid'), ['vm_uuid'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('backup', 'restore', 'verify', 'gc', name='taskkind', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'success', 'warning', 'failed', 'cancelled', name='taskstate', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', openbackup.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('bytes_total', sa.BigInteger(), nullable=False),
    sa.Column('bytes_read', sa.BigInteger(), nullable=False),
    sa.Column('bytes_written', sa.BigInteger(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_state'), ['state'], unique=False)

    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('at', openbackup.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.create_index('ix_task_logs_task_id_id', ['task_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_task_logs_task_id_id')

    op.drop_table('task_logs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_state'))
        batch_op.drop_index(batch_op.f('ix_tasks_job_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))

    op.drop_table('tasks')
    with op.batch_alter_table('restore_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restore_points_vm_uuid'))
        batch_op.drop_index(batch_op.f('ix_restore_points_repository_id'))
        batch_op.drop_index(batch_op.f('ix_restore_points_job_id'))
        batch_op.drop_index(batch_op.f('ix_restore_points_created_at'))

    op.drop_table('restore_points')
    op.drop_table('jobs')
    op.drop_table('datastore_access')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    op.drop_table('vcenters')
    op.drop_table('users')
    op.drop_table('repositories')
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_failures_ip'))
        batch_op.drop_index(batch_op.f('ix_login_failures_at'))

    op.drop_table('login_failures')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
